version: '3'

services:
  dbCats:
    image: postgres:15.3
    restart: always
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: catsdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
